### ISSUE TITLE
supporting desktop clients might be really simple

### ISSUE THREAD

**Issue by meandavejustice** [mozilla/email-tabs#1]
I just pulled this down to play with it and realized I could get it to launch my desktop email client without a recipient by just navigating to `mailto:?body="my%20tab%20url"`.

This opens up the question of how to determine whether to open a new gmail message or try the `mailto` approach. We could probably just let that be an option in settings.

Another issue with this approach(that may not be a big deal) is that you cannot put html into the body param for `mailto:` protocol links.

Feel free to close this, just thought i'd share :)

**Comment by ianb** [comment]
We'd have to have some setting. I definitely want to explore richer/fancier HTML emails, and there's no standard way to compose those, so for practicality's sake I am stuck with just gmail. Generating a text alternative would be easy enough, and the mailto link is simple to generate, but there'd have to be some UI to select that option or preference.

**Comment by ianb** [comment]
I think #31 (adding a Copy option) will be the answer to this for us – I want to keep the HTML and focus on that specifically, and the best way to handle this would be to copy the HTML and open an email.

One product I looked at relied on this specifically, opening `mailto:?body=Paste%20here` and then auto-copying. Maybe we could figure out a way to do that, if we can detect your default email.
