### ISSUE TITLE
Set focus and cursor position in email

### ISSUE THREAD

**Issue by ianb** [mozilla/email-tabs#101]
Right now when you compose the window, nothing has keyboard focus. Seems like something should.

We could put focus at the top of the message body. One annoyance is that in all our templates currently the top of the message body has a link. This means the link dialog pops up, and makes editing a bit more awkward:

<img width="784" alt="image" src="https://user-images.githubusercontent.com/44390/43280659-202abd32-90d7-11e8-9a79-8969486e76cd.png">

We might want to consider including a couple `<br>` at the top to give the user an easy place to write...?

**Comment by youwenliang** [comment]
We could add a line before all the links that says something like "A list of tabs sent via Email Tabs"

**Comment by ianb** [comment]
Let's just not do this for now. Recipients is focused by default, and that's fine.
