### ISSUE TITLE
Check with non-standard pages

### ISSUE THREAD

**Issue by ianb** [mozilla/email-tabs#110]
Specifically we should check what happens if you send an image (a direct link to an image) or a PDF

**Comment by ianb** [comment]
Examples... an image, just the links AND full article:

<img width="617" alt="image" src="https://user-images.githubusercontent.com/44390/44935891-21b3b780-ad38-11e8-81c0-f81f3d8dd9b4.png">

With screenshot:

![image](https://user-images.githubusercontent.com/44390/44935920-398b3b80-ad38-11e8-977e-138b0a40d9b6.png)

----------

PDF basically works in a stripped-down fashion. It doesn't get a screenshot, and it doesn't get a readable version.

----------

Arguably we should get a screenshot of a PDF (maybe we need an additional permission for this, ala Screenshots).

Should Full Article fall back to a screenshot?

**Comment by johngruen** [comment]
For Screenshots & Full Article View...
Show a screenshot and make the link below say "Original image"
