### ISSUE TITLE
Alt text appears confusingly during screenshot upload process

### ISSUE THREAD

**Issue by ianb** [mozilla/email-tabs#115]
This might be specific to the new Gmail design. Perhaps we should adjust the alt text before upload, to say something like "uploading..."

**Comment by johngruen** [comment]
Provisionally putting it in MVP

**Comment by johngruen** [comment]
@clouserw will check if it is an issue

**Comment by clouserw** [comment]
I didn't see the alt text -- I didn't see anything.  Just a blank white compose email screen for maybe....8-10 seconds.  Long enough that I thought it was broken.  We should do some kind of loading screen

**Comment by ianb** [comment]
Closing, as #130 should cover up any issue with this
