### ISSUE TITLE
Decide how Email Tabs should work in Private Browsing

### ISSUE THREAD

**Issue by ianb** [mozilla/email-tabs#122]
QA pointed this out: how do we want this to work in a Private Browsing mode window? It seems reasonable for it to work as normal (there are many points of confirmation), but it's unlikely that the compose window is going to work when opened in Private Browsing. Should we open it in another window? Just let it work as it works now, and force people to login in Gmail? How do mailto links work in Private Browsing?

**Comment by meandavejustice** [comment]
Maybe another prompt to ask the user if they want to open it in a non private browsing window?

**Comment by johngruen** [comment]
Decision: 

If a user is in PBM, we will only show the `copy links to clipboard` option. We should also add some messaging to describe why this is the case
