### ISSUE TITLE
Select Template Screen

### ISSUE THREAD

**Issue by youwenliang** [mozilla/email-tabs#123]
I open this issue as a place to put UX spec.

Measurements:
https://mozilla.github.io/testpilot-assets/EmailTabs/01_Measurements/EmailTabsv2/

Assets:
Logo(TBD): https://github.com/mozilla/testpilot-assets/tree/master/EmailTabs/00_Assets/Icon
Template Icons: https://github.com/mozilla/testpilot-assets/tree/master/EmailTabs/01_Measurements/EmailTabsv2/assets

**Comment by meandavejustice** [comment]
There should also be a cancel option on this screen, I'll just add it as linked text underneath the three template icons for now
