### ISSUE TITLE
Need default favicon

### ISSUE THREAD

**Issue by meandavejustice** [mozilla/email-tabs#125]
What should we show in place of a missing favicon in the panel?

![no-favicon-email-tabs](https://user-images.githubusercontent.com/1844554/45187525-7bc4e900-b220-11e8-8600-aca27d95c804.png)

**Comment by youwenliang** [comment]
I think we could use the globe icon from the [photon icon library](https://design.firefox.com/icons/viewer/).
This one: 
![image](https://user-images.githubusercontent.com/8919308/45273854-1e15f280-b4e7-11e8-9449-c92fbd048918.png)
