### ISSUE TITLE
Fix template selector cancel button

### ISSUE THREAD

**Issue by ianb** [mozilla/email-tabs#136]
It's squashy:

<img width="855" alt="image" src="https://user-images.githubusercontent.com/44390/45838357-246e5080-bcd7-11e8-82a3-634e8d7e5970.png">

**Comment by meandavejustice** [comment]
@ianb can I get a lil more info on this one?

**Comment by youwenliang** [comment]
@meandavejustice Checkout the measurement here:
https://mozilla.github.io/testpilot-assets/EmailTabs/01_Measurements/EmailTabs_Update/#artboard8

**Comment by meandavejustice** [comment]
fixed in #147

**Comment by youwenliang** [comment]
@meandavejustice I think we should also remove 'PT Sans Narrow', sans-serif from the button element.
