### ISSUE TITLE
Update modal messages design on new tab

### ISSUE THREAD

**Issue by youwenliang** [mozilla/email-tabs#143]
Here:

Not logged in to Gmail:
https://mozilla.github.io/testpilot-assets/EmailTabs/01_Measurements/EmailTabs_Update/#artboard6

Offline:
https://mozilla.github.io/testpilot-assets/EmailTabs/01_Measurements/EmailTabs_Update/#artboard5

After tabs sent:
https://mozilla.github.io/testpilot-assets/EmailTabs/01_Measurements/EmailTabs_Update/#artboard7

**Comment by ianb** [comment]
We should do "After tabs sent", but the other two are hard for us to actually catch/intercept.
