### ISSUE TITLE
Add iconUrl  and title to notifications

### ISSUE THREAD

**Issue by meandavejustice** [mozilla/email-tabs#154]
https://github.com/mozilla/email-tabs/blob/master/addon/background.js#L176

**Comment by meandavejustice** [comment]
@johngruen ^

**Comment by meandavejustice** [comment]
Figured out the fill issue, but we need a better quality svg for the notifications as it wants `96 x 96`.
Setting the height and width in the svg still shows a blurry. John said this may be that windows rasterizes the svg before putting it in the icon.

Waiting on new svg.

**Comment by johngruen** [comment]
@meandavejustice do those work?

![light](https://user-images.githubusercontent.com/3323249/47586815-2a3aff80-d92f-11e8-9115-0b59a49c043a.png)
![dark](https://user-images.githubusercontent.com/3323249/47586817-2b6c2c80-d92f-11e8-87dd-c75fe080f03c.png)
