### ISSUE TITLE
You are wrongly redirected to the "Compose Mail" page after you log in into your Gmail Account

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/email-tabs#169]
**[Affected versions]:**
- Firefox 62.0.3 and above

**[Affected Platforms]:** 	 	
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Email Tabs" add-on (0.1.6758) custom built on 10/09/2018 installed.
- You are not logged in to Gmail.
- Have a website opened in the browser.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and click the "Email-Tabs" toolbar button.
2. Click the "Email Tabs" button.
3. Log into your Google account and observe the behavior.

**[Expected result]:**
- You are redirected to "Select an email template" page.

**[Actual result]:**
- You are redirected to "Compose email page" page.

**[Notes]:**
- Attached is a screen recording of the issue: 

![notloggedin](https://user-images.githubusercontent.com/40061643/46747258-7b08f200-ccb9-11e8-9970-fa8dfde8b814.gif)

**Comment by ianb** [comment]
We lose track of the pages when you are going through the login page, and it's hard to recover. I believe there should be a popup notification that tells you to re-try sending the articles after you log in to your email.
