### ISSUE TITLE
The template page appears after a great delay if more than 10 tabs are sent

### ISSUE THREAD

**Issue by Softvision-PatriciuPop** [mozilla/email-tabs#172]
[Notes]:
- Emailing unloaded tabs almost doubles the load time.
- The loading time is increased with the number of tabs.

[Affected versions]:
- Firefox Nightly Version 64.0a1, Build ID 20181010235834
- Firefox Beta Unbranded Version 63.0b12, Build ID 20181004174654
- Firefox Release Unbranded Version 62.0.3, Build ID 20181001155545

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- extensions.legacy.enabled pref is set to true
- xpinstall.signatures.required pref is set to false
- User is logged in with a Gmail account
- Latest Email Tabs version is installed (0.1.6799)

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Open 10 websites in new tabs.
3. Click the "Email tabs" button and click the select all button.
4. Click the "Email tabs" button and observe the behavior.

[Expected result]:
- The page is loading and the templates page is displayed.

[Actual result]:
- The email draft is displayed before the template page is loaded.

[Additional Notes]:
- The issue is reproducible only when sending 10 tabs or more.
- Loading times until the templates page is shown below:

| Nightly - loaded tabs | Nightly - unloaded tabs |
| ------------- | ------------- |
| 5 tabs: 5.01s | 5 tabs: 2.11s |
| 10 tabs: 6.93s  | 10 tabs: 11.39s |
| 15 tabs: 9.36s  | 15 tabs: 11.20s |
| 20 tabs: 11.10s  | 20 tabs: 23.32s |
| 25 tabs: 15.04s  | 25 tabs: 29.11s |

| Beta Unbranded - loaded tabs | Beta Unbranded - unloaded tabs |
| ------------- | ------------- |
| 5 tabs: 3.45s | 5 tabs: 6.38s |
| 10 tabs: 5.66s  | 10 tabs: 10.62s |
| 15 tabs: 7.89s  | 15 tabs: 15.76s |
| 20 tabs: 10.77s  | 20 tabs: 22.79s |
| 25 tabs: 14.32s  | 25 tabs: 29.29s |

| Release Unbranded - loaded tabs | Release Unbranded - unloaded tabs |
| ------------- | ------------- |
| 5 tabs: 3.71s | 5 tabs: 3.85s |
| 10 tabs: 5.96s  | 10 tabs: 11.54s |
| 15 tabs: 8.79s  | 15 tabs: 17.77s |
| 20 tabs: 11.15s  | 20 tabs: 22.17s |
| 25 tabs: 12.99s  | 25 tabs: 28.02s |

- I have attached a screen recording of the issue:
![email tabs delay](https://user-images.githubusercontent.com/40393891/46811171-e961b900-cd7a-11e8-8eb7-0f470827ebc3.gif)

**Comment by ianb** [comment]
The problem is with this blocking call that happens before we start the load script: https://github.com/mozilla/email-tabs/blob/master/addon/background.js#L128

**Comment by Softvision-PatriciuPop** [comment]
I have verified that this issue is no longer reproducible using email_tabs-0.1.7232 on Windows 10 x64, Mac 10.13 and Arch Linux using Firefox Nightly Version 65.0a1, Build ID 20181028102553.
