### ISSUE TITLE
Add email provider preference

### ISSUE THREAD

**Issue by ianb** [mozilla/email-tabs#174]
If you open the panel and you have not selected a default email provider, then we will replace the panel with a selector for Gmail, Yahoo, or Outlook (and a sorry message for people who use something else).

After, there will be a gear icon in the panel which will take you back to the preference. It will go in the upper right (alongside Select All)

**Comment by youwenliang** [comment]
Something like this?
https://mozilla.invisionapp.com/share/2WOJL686TJE

**Comment by ianb** [comment]
Behavior is done in #190, but it's not styled properly. Other functionality in #190 is also not done (the actual support for other mail providers), so that PR will sit for a little time while we attend to other matters.
