### ISSUE TITLE
The screenshot from the email preview is cloned when dragging and dropping it inside the email's content

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/email-tabs#180]
[Affected versions]:
- Firefox 62.0.3 and above

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest version of the "Email Tabs" add-on (0.1.6822) custom built on 10/15/2018 installed.
- You are logged into the Gmail account.
- Have a website opened in the browser.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and click the "Email-Tabs" toolbar button.
2. Click the "Email Tabs" button.
3. Select the following email template: "Link with Screenshots".
4. Drag and drop the screenshot anywhere on the email's content.
5. Observe the behavior.

[Expected result]:
- The image moves on the spot on which is dropped.

[Actual result]:
- The image is cloned: the first one remains on its initial place and the second one is moved on the spot where the first one was supposed to be dropped.

[Notes]:
- This issue is reproducible only at the first drag and drop.
- This issue is also reproducible if there are more than one screenshots in the preview email.
- Attached is a screen recording of the issue:

![email tabs](https://user-images.githubusercontent.com/26000308/46957680-bbdd7e00-d0a0-11e8-9861-a6c57073b9b6.gif)

**Comment by meandavejustice** [comment]
I think this is unavoidable, as it is the default `ondropevent` behavior with images for the compose window.

**Comment by ianb** [comment]
OK, sounds like this is just how Gmail works.
