### ISSUE TITLE
The buttons from the Gmail notification, that is displayed after an email was sent, are not working at all

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/email-tabs#183]
**[Affected versions]:**
- Firefox 62.0.3 and above

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Email Tabs" add-on (0.1.6920) custom built on 10/16/2018 installed.
- You are logged in to "Gmail".

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Navigate to any website and click the "Email Tabs" toolbar button.
3. Click the "Email Tabs" button and select any template.
4. Insert a valid email in the "Recipients" field and click the "Send" button.
5. Click any button from the displayed notification and observe the behavior.

**[Expected result]:**
- The notification's buttons are working as expected.

**[Actual result]:**
- The notification's buttons are not working at all.

**[Notes]:**
- This issue is not reproducible if the email was sent without using the "Email Tabs" experiment.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/47022713-c4988780-d166-11e8-8e78-73a027d600a8.gif)

**Comment by Softvision-PatriciuPop** [comment]
I have verified that this issue is no longer reproducible using email_tabs-0.1.7232 on Windows 10 x64, Mac 10.13 and Arch Linux using Firefox Nightly Version 65.0a1, Build ID 20181028102553.
