### ISSUE TITLE
The "Email Tabs" signature is wrongly copied to the clipboard, together with the selected tabs, if the "Copy Tabs to Clipboard" button is clicked 

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/email-tabs#184]
**[Affected versions]:**
- Firefox 62.0.3 and above

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Email Tabs" add-on (0.1.6920) custom built on 10/16/2018 installed.
- You are logged in to "Gmail".

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Navigate to any website and click the "Email Tabs" toolbar button.
3. Click the "Copy Tabs to Clipboard" button and open any text editor (eg. Gdoc).
4. Paste the content from the clipboard and observe the behavior.

**[Expected result]:**
- The name of the selected tabs is pasted and it is hyperlinked.

**[Actual result]:**
- The "Email Tabs" signature is also pasted.

**[Notes]:**
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/47023512-7b493780-d168-11e8-9aaa-eb8ab0c7ada8.gif)

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue using the latest version of the "Email Tabs" add-on (0.1.7232) custom built and the issue is no longer reproducible. Tested on Windows 10 x64, Mac 10.13 and Ubuntu 18.04 x64.
