### ISSUE TITLE
Certain websites display only a random part of the content as full article if choosing the "Link with Full Articles" option

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/email-tabs#187]
**[Affected versions]:**
- Firefox 62.0.3 and above

**[Affected Platforms]:** 	 	
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Email Tabs" add-on (0.1.6942) custom built.
- You are logged in to Gmail.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Navigate to https://edition.cnn.com/ website.
2. Click the "Email-Tabs" toolbar button.
3. Click the "Email Tabs" button.
4. Select the "Link with Full Articles" option and observe the mail's content.

**[Expected result]:**
- The link and the full articles of the website are displayed.

**[Actual result]:**
- The source and a random part of the content are displayed.

**[Notes]:**
- Here is a list of websites that don't sent the full content: https://edition.cnn.com/; https://www.reddit.com/; https://www.theverge.com/; https://world.taobao.com/; 
- This is also reproducible with search results from Google and Yahoo search engines.
- This issue is not reproducible on search results using the Bing search engine.
- This issue is not reproducible if you navigate to an article from the mentioned pages, the full content is correctly displayed.
- Attached is a screen recording of the issue: 
![lesscontent](https://user-images.githubusercontent.com/40061643/47084855-7c886c00-d21d-11e8-9a1b-d107ec5c6248.gif)

**Comment by ianb** [comment]
I think we need to detect proper "articles" and only try to do a readable mode extraction of those articles. Firefox does this, and only shows the Reader Mode icon for appropriate pages. I'm not sure what that detection is based on, but we should find it.

If we can't use Readability, then we should fall back to a screenshot for that page.

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue using the latest version of the "Email Tabs" add-on (0.1.7232) custom built and the issue is still reproducible on https://www.reddit.com/. However, this issue is no longer reproducible on the other websites enumerated in notes or results from search engines, the content is sent as screnshoots.
Tested on Windows 10 x64, Mac 10.13 and Ubuntu 18.04 x64.

**Comment by ianb** [comment]
`isProbablyReaderable()` returns true for reddit.com. This isn't really correct, of course, but it's at best a heuristic. I think we should accept it won't work correctly on every site.

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue using the latest Email Tabs (0.1.7280) custom build and the issue is no longer reproducible. Tested on Windows 10 x64, Mac 10.13 and Ubuntu 18.04 x64.
