### ISSUE TITLE
The Email Tabs doorhanger goes blank when showing the browser window in full screen mode

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/email-tabs#208]
**[Affected versions]:**
- Firefox Release 63.0 and above

**[Affected Platforms]:** 	 	
- All Windows

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Email Tabs" add-on (0.1.7280) custom built.
- The browser was previously resized.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites
2. Click the "Email-Tabs" toolbar button.
3. Press "F11" key and observe the doorhanger.

**[Expected result]:**
- The doorhanger renders correctly with full screen.

**[Actual result]:**
- The doorhanger goes blank.

**[Notes]:**
- Attached is a screen recording of the issue: 
![blank](https://user-images.githubusercontent.com/40061643/47800710-81790f80-dd35-11e8-9ff9-45a62f68db6f.gif)

**Comment by meandavejustice** [comment]
This seems to happen whenever changing the window size, it happens when I do the `windowskey-leftArrow` or `windowsKey-rightArrow` to achieve a sort of tiled window manager effect

**Comment by meandavejustice** [comment]
There is an additional issue here where the popup can be orphaned when moved twice.
![orphaned-webext-popup](https://user-images.githubusercontent.com/1844554/47814372-6dd5a500-dd45-11e8-9c09-74a276c733be.png)

I'm seeing this with almost all of the webextensions, ublock origin, privacy badger, no more 404s etc...
Gunna poke around in bugzilla and see if I can locate an issue to track.

Separately, weirdness around popups and context menus seems to be common for me in both windows and linux. a lot of times I will have a context menu open, switch apps to front and center and still have the context menu or popup above my new app(usually see this with emacs, but others also). Which will stay around until I return firefox into focus and `<esc>` the popup/context menu away.

**Comment by meandavejustice** [comment]
Closing as this has a bugzilla bug.

**Comment by Softvision-RemusDranca** [comment]
Seems to be an old regression, using the mozregression tools, I have got a pushlog: https://tinyurl.com/y7sljqou.
Unfortunately, I didn't manage to go further since there are very old builds. So probably one of the issues from the pushlog introduced this.
