### ISSUE TITLE
The "Sorry we don't support any other mail providers. Learn more" message is missing from the "Select Default Mail Provider" doorhanger

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/email-tabs#218]
**[Affected versions]:**
- Firefox 63.0.1 and above

**[Affected Platforms]:** 	 	
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a new Firefox profile with the latest version of the "Email Tabs" add-on (0.1.7327) custom built.
- You are not logged in to Gmail.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites
2. Click the "Email-Tabs" toolbar button.
3. Observe the section under the email providers.

**[Expected result]:**
- The "Sorry we don't support any other mail providers. Learn more" message is displayed.

**[Actual result]:**
- No message is displayed, only a line under the email providers section.

**[Notes]:**
- Based on the mock-ups the "Sorry we don't support any other mail providers. Learn more" message should be displayed under the the email providers buttons.
- The message was displayed in add-on version (0.1.7280), when the UI for email providers wasn't implemented.
- Attached is a screen recording of the issue: 
![string](https://user-images.githubusercontent.com/40061643/47925825-bd43de80-dec7-11e8-9bd1-ac1e945b31b5.gif)

**Comment by meandavejustice** [comment]
![sorry-msg](https://user-images.githubusercontent.com/1844554/48016389-663a4580-e123-11e8-92c8-67c99839d170.png)

added this in a branch, need to figure out where we want the "Learn more" link to point at. @ianb

**Comment by ianb** [comment]
Once #227 lands, https://github.com/mozilla/email-tabs/blob/master/docs/faq.md#mail-providers should work

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue using the latest Email Tabs (0.1.7448) custom build and the issue is no longer reproducible. Tested on Windows 10 x64, Mac 10.13 and Ubuntu 18.04 x64.
