### ISSUE TITLE
The "Sign in to your email account..." notification is displayed inconsistently

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/email-tabs#219]
**[Affected versions]:**
- Firefox 63.0.1 and above

**[Affected Platforms]:** 	 	
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Email Tabs" add-on (0.1.7327) custom built.
- You are not logged in to Gmail.
- Have a website opened in the browser.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "Email-Tabs" toolbar button.
3. Click the "Email Tabs" button and observe the notification message.
4. Click again on the "Email-Tabs" toolbar button.
5. Click the "Email Tabs" button and observe if the notification message is redisplayed.

**[Expected result]:**
3. The notification message is displayed.
5. The notification message is redisplayed.

**[Actual result]:**
3. The notification message is displayed.
5. The notification message is NOT redisplayed.

**[Notes]:**
- The notification is correctly re-displayed if you wait ~10 seconds before the second attempt. Is there a timing implemented regarding how often the notification should be displayed if the users try again to Email a website?
- Here is a [link](https://drive.google.com/open?id=1tS8OzJ8fayiNIlNjhIr1RQ95uMrmpeih) with the screen recording of the issue:

**Comment by ianb** [comment]
There is a time limit in place, it's supposed to be 30 seconds. This is to avoid some error condition that blasts error messages at the user. As such, I'll wontfix this as intentional.
