### ISSUE TITLE
Email tabs vs Email Tabs

### ISSUE THREAD

**Issue by pdehaan** [mozilla/email-tabs#222]
Randomly spotted while closing tabs and this was a previous comment in https://github.com/mozilla/testpilot/pull/3934#discussion_r230441541

https://github.com/mozilla/email-tabs/blob/108586b1ec48d67d12cb8bbc12cf75666fa87f2c/addon/manifest.json.tmpl#L38

**Comment by pdehaan** [comment]
And there may be 2 more usages in index.html

```sh
git grep -n --heading --break "Email tabs"
```

#### addon/manifest.json.tmpl
- [ ] 34:    `"default_title": "Email tabs",`

#### index.html
- [ ] 11:    [`<title>Email tabs templates</title>`](https://github.com/mozilla/email-tabs/blob/108586b1ec48d67d12cb8bbc12cf75666fa87f2c/index.html#L11)
- [ ] 14:    [`<h1>Email tabs templates</h1>`](https://github.com/mozilla/email-tabs/blob/108586b1ec48d67d12cb8bbc12cf75666fa87f2c/index.html#L14)

**Comment by ianb** [comment]
Marnie got this fixed
