### ISSUE TITLE
Images are rendered as based64 if the tabs are sent with the "Yahoo" email provider

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/email-tabs#232]
[Affected Versions]:
-Firefox 63.0. and above

[Affected Platforms]:

- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest version of the "Email Tabs" add-on (0.1.7448) custom built.
- Have the Yahoo.com and Outlook.com email providers enabled from "about:addons" from Email Tabs add-on preferences
- Be logged into yahoo.com email provider website.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from the prerequisites and navigate to any website.
2. Click the "Email tabs" icon from the toolbar.
3. Click the gear icon and select the "Yahoo" email provider.
4. Click the "Email tabs" button.
5. Click the "Link with screenshots" thumbnail.
6. Add a valid email account and send the email tab.
7. Observe the image from the sent email tab.

[Expected result]:
- The image is correctly displayed.

[Actual result]:
- The image is rendered in base64.

[Notes]:
- This is also reproducible when sending links with full articles tab emails.
- Attached a screen recording of the issue: 

![rec of the issue - images as base 64](https://user-images.githubusercontent.com/37875464/48141213-168a8400-e2b3-11e8-9af5-2f4992a1df80.gif)

**Comment by ianb** [comment]
This isn't base64, it's #244 – the alt text looks like a jumble. There's a control to load images, and without it only the alt text is shown.
