### ISSUE TITLE
Elements from the email provider "New message" page are wrongly focused when navigating with the "Tab" key on the "Select an email template" page

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/email-tabs#235]
[Affected Versions]:
-Firefox 63.0. and above

[Affected Platforms]:

- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest version of the "Email Tabs" add-on v0.1.7463.
- Have the Yahoo.com and Outlook.com email providers enabled from "about:addons" from Email Tabs add-on preferences
- You are logged into "Gmail"

[Steps to reproduce]:
1. Open the Firefox browser with the profile from the prerequisites and navigate to any website.
2. Click the "Email tabs" icon from the toolbar.
3. Click the "Email tabs" button.
4. Navigate on the page with the "Tab" key and observe the focused elements.

[Expected result]:
- Only the displayed elements are focused.

[Actual result]:
- Invisible elements from the email "New message" page are focused and description of them are displayed.

[Notes]:
- This issue cannot be verified on "Yahoo" and "Outlook" email providers due to issue: [#230](https://github.com/mozilla/email-tabs/issues/230)
- Attached a screen recording of the issue:

![rec of the issue - keyboard navigation](https://user-images.githubusercontent.com/37875464/48199473-c409a000-e364-11e8-922c-e141dd0c57fd.gif)

**Comment by ianb** [comment]
We should put the keyboard focus into the iframe. Screenshots does an explicit focus for this same reason. We should be sure there are tabindexes, and @johngruen is going to handle that in a PR.

**Comment by Softvision-AndreeaCupsa** [comment]
This issue is still reproducible with the latest custom build (v0.1.7568) on Windows 10 x64, Arch Linux and Mac 10.13.3. At first the elements from the "Select an email template" page are correctly focused, but if you continue pressing the "Tab" key the elements from the "New message" page can still be focused.

Considering this I will reopen this issue.

**Comment by johngruen** [comment]
We think there's no 100% fix here
