### ISSUE TITLE
The "Sign in your email account..." system notification is no longer displayed when you click the "Email Tabs" button when you are not logged in to your email provider

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/email-tabs#236]
**[Affected versions]:**
- Firefox 63.0.1 and above

**[Affected Platforms]:** 	 	
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a new Firefox profile with the latest version of the "Email Tabs" add-on (0.1.7463) signed, downloaded from ([link](https://testpilot.firefox.com/files/email-tabs@mozilla.org/signed-addon.xpi)).
- You are not logged in your email provider.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to "https://www.wikipedia.org/".
2. Click the "Email-Tabs" toolbar button. 
3. Select the "Gmail" option.
4. Click the "Email Tabs" button and observe if any system notification is displayed.

**[Expected result]:**
- The "Sign in your email account..." system notification is displayed.

**[Actual result]:**
- No notification is displayed.

**[Notes]:**
- This issue is also reproducible if the Yahoo Mail or Outlook provider is selected.
- If you click the "Email-Tabs" toolbar button, after running the "Steps to reproduce", the "Don't forget to sign..." message is also not displayed in the doorhanger.
- Attached is a screen recording of the issue: 
![notification](https://user-images.githubusercontent.com/40061643/48210635-671be300-e380-11e8-9899-2dd615171cb0.gif)

**Comment by ianb** [comment]
I'll try to fix this for release. But generally we won't consider login notifications to be a blocker for this release.

**Comment by johngruen** [comment]
Agree

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue using the latest Email Tabs (0.1.7497) custom build and the issue is no longer reproducible. Tested on Windows 10 x64, Mac 10.13 and Ubuntu 18.04 x64.
