### ISSUE TITLE
The "Email Tabs" addon is no longer displayed in the toolbar after reinstall if it was previously removed from the toolbar

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/email-tabs#246]
**[Affected versions]:**
- Firefox 63.0.1 and above

**[Affected Platforms]:** 	 	
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a new Firefox profile with the latest version of the "Email Tabs" add-on (0.1.7463) signed, downloaded from ([link](https://testpilot.firefox.com/files/email-tabs@mozilla.org/signed-addon.xpi)).

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Right click on the "Email-Tabs" toolbar button and select the "Remove from toolbar" option.
3. Navigate to the "about:addons" page, "Extension" section and remove the "Email Tabs" experiment. 
4. Reinstall the "Email Tabs" experiment trough the "about:addons" page.
5. Observe the addons section from the toolbar.

**[Expected result]:**
- The "Email Tabs" toolbar button is displayed in the toolbar.

**[Actual result]:**
- The "Email Tabs" toolbar button is not displayed in the toolbar.

**[Notes]:**
- This issue is also reproducible if the browser is restarted after the addon has been removed from the toolbar.
- Attached is a screen recording of the issue: 
![toolbar](https://user-images.githubusercontent.com/40061643/48255784-528a2a00-e416-11e8-8cf7-f91c82a5b03b.gif)

**Comment by johngruen** [comment]
This is default add-on behavior i believe.

**Comment by johngruen** [comment]
Verified...
@Softvision-RemusDranca maybe this should be a webextensions bug in bugzilla? I am closing as a wontfix
