### ISSUE TITLE
Why is only Gmail supported?

### ISSUE THREAD

**Issue by rockhopper72** [mozilla/email-tabs#268]
In the [README](https://github.com/mozilla/email-tabs/blob/master/README.md), it says:

> Note that only Gmail is supported, because there's no general standard for composing HTML emails.

as well as the [FAQ](https://github.com/mozilla/email-tabs/blob/master/docs/faq.md):

> ### Why does this only support Gmail?
> 
> There's no standard for composing rich emails. 

I don't understand how there is no standard for composing rich emails? Is that not what the [mailto:](https://tools.ietf.org/html/rfc6068) link is for?

For example,

```
mailto:john@example.com?body=Message%20body
```

becomes [clickable](mailto:john@example.com?body=Message%20body).

Pardon my ignorance if I'm missing something. Thanks!

**Comment by ianb** [comment]
The mailto links are clickable, but the email it generates is plain text. Like [this example](mailto:john@example.com?body=%3Ca%20href%3D%22http%3A%2F%2Fexample.com%22%3Elink%20to%20example.com%3C%2Fa%3E) – it puts the text `<a href="http://example.com">link to example.com</a>` in the body, not an actual link.

**Comment by rockhopper72** [comment]
Ah, my bad! Thanks for the response.
