### ISSUE TITLE
Wake up tabs before sending

### ISSUE THREAD

**Issue by ianb** [mozilla/email-tabs#28]
If you select a tab that isn't awake (like you haven't visited it since restarting the browser) then the content script will never attach and nothing will happen. We have to do something to make sure the tabs are awake and active.

**Comment by ianb** [comment]
The issue here is a tab that has been [discarded](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/discard). I'm investigating, but at the moment while you can read the discarded state of a tab, it's unclear if you can wake the tab up except by activating it (which of course we could do).

**Comment by mixedpuppy** [comment]
Specifically, see docstring here:

https://searchfox.org/mozilla-central/rev/292d295d6b084b43b70de26a42e68513bb7b36a3/browser/base/content/tabbrowser.js#113-121
