### ISSUE TITLE
Check emails with Litmus

### ISSUE THREAD

**Issue by ianb** [mozilla/email-tabs#35]
The [Litmus](http://litmus.com/) service checks emails to see if they are formatted well for various email clients. We support writing in Gmail, but anyone can read it anywhere.

Mozilla has an account we can make use of. [This google doc](https://docs.google.com/document/d/17TWKutMwke3K4sdJryMr23BVYAvWIK9CjaK34I9H42s/edit#) gives the information (visible only to Mozilla employees).

**Comment by johngruen** [comment]
@meandavejustice can you do one of each template with 5 sites and 10 sites

**Comment by meandavejustice** [comment]
* [5 Sites, Screenshots Template](https://litmus.com/pub/8037150)
* [5 Sites, Full Article Template](https://litmus.com/pub/a569cd4)
* [5 Sites, Just links Template](https://litmus.com/pub/80ed243)

* [10 Sites, Screenshots Template](https://litmus.com/pub/12c51b8)
* [10 Sites, Full Article Template](https://litmus.com/pub/38265ce)
* [10 Sites, Just Links Template](https://litmus.com/pub/9da052e)
