### ISSUE TITLE
Review Style of message compose completed buttons

### ISSUE THREAD

**Issue by ianb** [mozilla/email-tabs#36]
~~This is an update to 63a428eb2ece765ada7f18e88e0af6b81b0a342e (#29). The buttons are pretty simple now:~~

#### See latest comment for updated style, review needed

<img width="607" alt="image" src="https://user-images.githubusercontent.com/44390/41182734-8d78b422-6b3c-11e8-8f2b-196c93fe6a7e.png">

The relevant code is here: https://github.com/mozilla/email-tabs/blob/63a428eb2ece765ada7f18e88e0af6b81b0a342e/addon/set-html-email.js#L104-L117

**Comment by johngruen** [comment]
@sevaan let's walk through this thing next week and figure this stuff out

**Comment by ianb** [comment]
Note these are now implemented in `gmail-iframe.html`, which is more-or-less a standalone document that you can (re)style.

**Comment by meandavejustice** [comment]
Here is a screenshot of the changes added in #94 
![email-tabs-completed-draft](https://user-images.githubusercontent.com/1844554/43224241-30f46a38-9045-11e8-8c14-5f912992eede.png)

**Comment by ianb** [comment]
Any more work on this will be in a followup issue
