### ISSUE TITLE
Fancy UI

### ISSUE THREAD

**Issue by johngruen** [mozilla/email-tabs#39]
https://mozilla.github.io/testpilot-assets/

(hint: scroll to bottom)

**Comment by ianb** [comment]
Primarily we want:

![this image](https://mozilla.github.io/testpilot-assets/EmailTabs/01_Measurements/EmailTabsv1/preview/page-1-panels.png?1531245755180)

We aren't doing search (per #40).

**Comment by ianb** [comment]
To-do after cd2985145622d90d1c6ce3e57b7dba498d1638b4:

- [ ] Color the Email Tabs button
- [ ] Add a disabled state to the Email Tabs button (including disabling it when it should be disabled)
- [ ] Some hover style on those buttons
- [ ] Confirm exact style of Select All

**Comment by meandavejustice** [comment]
I got a branch going for these changes

**Comment by meandavejustice** [comment]
Finally getting back into finish this up
