### ISSUE TITLE
Implement email template chooser

### ISSUE THREAD

**Issue by ianb** [mozilla/email-tabs#41]
We want to experiment with a couple different email templates. To do this, let's have a drop-down/select box in the popup.

While we might want UX input here, we can start with a simple select box next to "Select All" in the popup.

**Comment by ianb** [comment]
Done in #78 except for styling of the chooser.

**Comment by sevaan** [comment]
Maybe an option like this would be smoother to use:

![template options 2x](https://user-images.githubusercontent.com/473531/42839158-ca30e0b2-89d0-11e8-87ef-3311e510433a.png)

**Comment by ianb** [comment]
We're going to use an interstitial page. So when you click "Email Tabs" it will open a page of ours (i.e., moz-extension:...), that page will have a big template chooser, and clicking on a template will compose an email using that template.

For now Copy Tabs to Clipboard will always use the Links Only template.
