### ISSUE TITLE
Add feedback link

### ISSUE THREAD

**Issue by ianb** [mozilla/email-tabs#47]
#39 has some design, but it doesn't include a feedback link

**Comment by johngruen** [comment]
@sevaan ?

**Comment by ianb** [comment]
I've created team-email-tabs@mozilla.com as an initial target for feedback, until we have a survey.

**Comment by sevaan** [comment]
Couple options:

![feedback 2x](https://user-images.githubusercontent.com/473531/42772718-4325b110-88f9-11e8-8991-20cd0ad8bbbe.png)

Option A uses the feedback mechanism we use in the corner of the Send website.
Option B is just text in the panel.

Thoughts?

**Comment by ianb** [comment]
Option B is what we'll do

**Comment by sevaan** [comment]
Text is:
```
font-size: 11px;
color: #4A4A4F;
letter-spacing: -0.08px;
```
