### ISSUE TITLE
Square icon needed

### ISSUE THREAD

**Issue by ianb** [mozilla/email-tabs#59]
The current icon (https://github.com/mozilla/email-tabs/blob/master/addon/emailtabs.svg) is not square. The addon-linter complains, and I think it might actually cause problems.

Also I think we need a style so it inherits colors. E.g.:

<img width="124" alt="image" src="https://user-images.githubusercontent.com/44390/42650876-42cf13ce-85d3-11e8-8648-9f4f0d11aebb.png">

(It's an SVG property/style we use in the Screenshots icon)

**Comment by johngruen** [comment]
@sevaan where did this icon come from?

**Comment by sevaan** [comment]
I made the icon. If I add the padding to make it square will that work?

[emailtabsicon.zip](https://github.com/mozilla/email-tabs/files/2198540/emailtabsicon.zip)

**Comment by ianb** [comment]
Yes, padding should work

**Comment by sevaan** [comment]
https://github.com/mozilla/testpilot-assets/tree/master/EmailTabs/00_Assets/Icon
