### ISSUE TITLE
Support Yahoo Mail and maybe Outlook

### ISSUE THREAD

**Issue by ianb** [mozilla/email-tabs#6]
According to [these stats](https://www.statista.com/statistics/547531/e-mail-provider-ranking-consumer-usa-age/) Yahoo Mail and Outlook/Hotmail are pretty widely used (even if Gmail is still most preferred). We might want to support them. This would probably require a setting for the email provider, though maybe we could guess or use the value in Preferences > General > Applications > mailto.

We should do an engineering outline with a manual selection.

**Comment by johngruen** [comment]
how hard is this?

**Comment by ianb** [comment]
Recreated in #176
