### ISSUE TITLE
Add context menu option

### ISSUE THREAD

**Issue by meandavejustice** [mozilla/email-tabs#72]
Should probably add an option to launch the panel from right clicking on tabs, especially since we already have a "send tab to device" option in that context menu.

![ctx-menu](https://user-images.githubusercontent.com/1844554/42695374-c0ec4fca-86a4-11e8-8075-cffb4a24ba01.jpg)

**Comment by iamVP7** [comment]
Is it similar to #22

**Comment by meandavejustice** [comment]
@iamVP7 it is, thanks for pointing that out, closing as this is a dupe
