### ISSUE TITLE
Fill in subject line, at least sometimes

### ISSUE THREAD

**Issue by ianb** [mozilla/email-tabs#84]
It would be nice when sending a single email, if we fill in the email subject line. I'd recommend a default of `Fwd: {title}`

**Comment by sevaan** [comment]
How about:

`{x} Tabs from Firefox`

e.g. 12 Tabs from Firefox

**Comment by sevaan** [comment]
I don't think the "Fwd:" part is necessary.

I just looked at my open tabs, and the first tab is:

`"Online Shopping Canada: Everyday Low Prices at Walmart.ca!" and 11 other links`

Even if you truncate the title, it still doesn't seem useful:

`'"Online Shopping Canada" and 11 other links'`

What if it was domain based?

`"Walmart.ca + 11 other links"`

**Comment by ianb** [comment]
We'll do `{og:title} and N links` (obviously without N links if there's just one link)
