### ISSUE TITLE
Give thumbnails a border or something

### ISSUE THREAD

**Issue by ianb** [mozilla/email-tabs#9]
The relevant code is here: https://github.com/ianb/email-tabs/blob/4d7230398896b8ee6c10b5d98dcb39291354f506/addon/sidebar.jsx#L104-L123

Many pages have white backgrounds or borders, and these blend into the email. It makes it look bad. A dropshadow or other style (applied inline to the `<img>`) would help.

**Comment by ianb** [comment]
Apparently Gmail wipes the inline style when it uploads the image. After the image is uploaded you can reapply a style, and that style will be honored. But to do it we'll have to watch Gmail's upload to see when the new image appears, then reapply styles from there.

**Comment by ianb** [comment]
The shadow is in there, but is wiped when actually reading the email.

**Comment by sevaan** [comment]
The spec has a border in the spec that isn't a shadow. Try this:

border: 1px solid rgba(12,12,13,0.10);
